[tool.poetry]
name = "min-symaskin-inventory-utils"
version = "0.1.0"
description = ""
authors = ["morten.aslesen <mortendaehli@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
ShopifyAPI = "^10.0.0"
python-dotenv = "^0.19.2"
openpyxl = "^3.0.9"
pandas = "^1.3.5"
typer = "^0.4.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
